name: deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and deploy Kucher
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve repository
        uses: actions/checkout@v1
      - name: Setup Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: Build the release using pyinstaller like in the build_linux.sh script
        continue-on-error: false
        run: |
            pip install -r requirements.txt
            pip install -r requirements-dev-linux.txt
            pyinstaller --clean --noconfirm pyinstaller.spec || exit 2
      - name: Deploy the release
        if: ${{ success() }}
        run: |
            KUCHER_VERSION=$(python3 -c "from kucher.version import __version__; print('.'.join(map(str, __version__)))")
            KUCHER_TARGET_DIR=/var/www/files/products/com.zubax.kucher/$KUCHER_VERSION/linux-x86_64
            ssh target "mkdir -p $KUCHER_TARGET_DIR; echo $KUCHER_TARGET_DIR"
            scp $KUCHER_ARTIFACT target:$KUCHER_TARGET_DIR
        env:
          KUCHER_ARTIFACT: dist/Kucher
