name: deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-18.04
    steps:
      - name: Retrieve repository
        uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: files.zubax.com
          SSH_USER: ubuntu
          SSH_KEY: ${{ secrets.FILES_RELEASE_SSH_PRIVATE_KEY }}
      - name: Extract the version number from version.py
        run: |
            -  echo "KUCHER_VERSION=$(python -c "from kucher.version import __version__; print('.'.join(map(str, __version__)))")" >> $GITHUB_ENV
      - name: Assemble the target directory path
        run: |
            - echo "KUCHER_TARGET_DIR=/var/www/files/products/com.zubax.kucher/$(KUCHER_VERSION)" >> $GITHUB_ENV
      - name: Build the release using pyinstaller like in the build_linux.sh script
        run: |
            pip install -r requirements.txt
            pip install -r requirements-dev-linux.txt
            pyinstaller --clean --noconfirm pyinstaller.spec || exit 2
      - name: Deploy the release
        run: |
#            ssh target "if [ -d $ ]; then sudo rm -rf $TARGET_DIR; fi"
            scp dist/Kucher target:$KUCHER_TARGET_DIR